//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NgVanDuoc2210900016.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NVD_SACH
    {
        [Display(Name ="Mã sách")]
        public string Nvd_MaSach { get; set; }
        [Display(Name = "Tên sách")]
        public string Nvd_TenSach { get; set; }
        [Display(Name = "S? trang")]
        public Nullable<int> Nvd_SoTrang { get; set; }
        [Display(Name = "N?m xu?t b?n")]
        public Nullable<int> Nvd_NamXB { get; set; }
        [Display(Name = "Mã tác gi?")]
        public string Nvd_MaTG { get; set; }
        [Display(Name = "Tr?ng thái")]
        public Nullable<bool> Nvd_TrangThai { get; set; }
    
        public virtual NVD_TACGIA NVD_TACGIA { get; set; }
    }
}
